### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by phalt** [scottlindeman/racketmon#1]
This looks fantastic, what's the progress on this?

If you need help let me know, I'm the creator of PokéAPI. I'd love to add it to the list of wrappers once this is completed!

**Comment by scottlindeman** [comment]
I'll say it's pretty usable now. Have some TODOs, but nothing major.

Feel free to add it to the list and thanks for checking it out!

**Comment by phalt** [comment]
Awesome! This looks brilliant, I'll open an issue on PokeAPI to add your wrapper to the list on the website.
